type: object
description: Specification of a Service Desk integration provisioning configuration.
properties:
  universalManager:
    description: Specifies whether this configuration is used to manage provisioning requests for all sources from the org.  If true, no managedResourceRefs are allowed.
    type: boolean
    readOnly: true
    example: true
  managedResourceRefs:
    description: References to sources for the Service Desk integration template.  May only be specified if universalManager is false.
    type: array
    items:
      $ref: '../../v3/schemas/BaseReferenceDto.yaml'
      default:
        type: SOURCE
  planInitializerScript:
    description: This is a reference to a plan initializer script.
    type: object
    properties:
      source:
        description: This is a Rule that allows provisioning instruction changes.
        type: string
        example: <rule code>
